identifier: k9w0o00816qb8390
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: scully-blog
homeFolder: /Users/msahl/Desktop/scully-markdown
distFolder: dist/scully-blog
outDir: /Users/msahl/Desktop/scully-markdown/dist/static
handle404: ''
allowErrorCollect: true
